# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
env:
  SOLUTION_PATH          : GymApp/
  IDENTITY_SERVER_PATH   : IdentityServer/
  GYM_BLAZOR_CLIENT_PATH : GYM.BlazorApp/
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore GymApp dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    - name: Restore Identity Server dependencies
      run: dotnet restore ${{ env.IDENTITY_SERVER_PATH }}
    - name: Restore GYM.BlazorApp restore
      run: dotnet restore ${{ env.IDENTITY_SERVER_PATH }}
  
    - name: Build GymApp
      run: dotnet build --no-restore ${{ env.SOLUTION_PATH }} 
    - name: Test
      run:  dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }} 
    - name: Build Identity Server
      run: dotnet build --no-restore ${{ env.IDENTITY_SERVER_PATH }} 
    - name: Build GYM.BlazorApp
      run: dotnet build --no-restore ${{ env.GYM_BLAZOR_CLIENT_PATH }} 
